// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// Setting is an object representing the database table.
type Setting struct {
	Key   null.String `boil:"key" json:"key,omitempty" toml:"key" yaml:"key,omitempty"`
	Value null.String `boil:"value" json:"value,omitempty" toml:"value" yaml:"value,omitempty"`

	R *settingR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L settingL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var SettingColumns = struct {
	Key   string
	Value string
}{
	Key:   "key",
	Value: "value",
}

var SettingTableColumns = struct {
	Key   string
	Value string
}{
	Key:   "settings.key",
	Value: "settings.value",
}

// Generated where

type whereHelpernull_String struct{ field string }

func (w whereHelpernull_String) EQ(x null.String) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_String) NEQ(x null.String) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_String) LT(x null.String) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_String) LTE(x null.String) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_String) GT(x null.String) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_String) GTE(x null.String) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelpernull_String) LIKE(x null.String) qm.QueryMod {
	return qm.Where(w.field+" LIKE ?", x)
}
func (w whereHelpernull_String) NLIKE(x null.String) qm.QueryMod {
	return qm.Where(w.field+" NOT LIKE ?", x)
}
func (w whereHelpernull_String) IN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelpernull_String) NIN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

func (w whereHelpernull_String) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_String) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

var SettingWhere = struct {
	Key   whereHelpernull_String
	Value whereHelpernull_String
}{
	Key:   whereHelpernull_String{field: "\"settings\".\"key\""},
	Value: whereHelpernull_String{field: "\"settings\".\"value\""},
}

// SettingRels is where relationship names are stored.
var SettingRels = struct {
}{}

// settingR is where relationships are stored.
type settingR struct {
}

// NewStruct creates a new relationship struct
func (*settingR) NewStruct() *settingR {
	return &settingR{}
}

// settingL is where Load methods for each relationship are stored.
type settingL struct{}

var (
	settingAllColumns            = []string{"key", "value"}
	settingColumnsWithoutDefault = []string{}
	settingColumnsWithDefault    = []string{"key", "value"}
	settingPrimaryKeyColumns     = []string{"key"}
	settingGeneratedColumns      = []string{}
)

type (
	// SettingSlice is an alias for a slice of pointers to Setting.
	// This should almost always be used instead of []Setting.
	SettingSlice []*Setting
	// SettingHook is the signature for custom Setting hook methods
	SettingHook func(boil.Executor, *Setting) error

	settingQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	settingType                 = reflect.TypeOf(&Setting{})
	settingMapping              = queries.MakeStructMapping(settingType)
	settingPrimaryKeyMapping, _ = queries.BindMapping(settingType, settingMapping, settingPrimaryKeyColumns)
	settingInsertCacheMut       sync.RWMutex
	settingInsertCache          = make(map[string]insertCache)
	settingUpdateCacheMut       sync.RWMutex
	settingUpdateCache          = make(map[string]updateCache)
	settingUpsertCacheMut       sync.RWMutex
	settingUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var settingAfterSelectMu sync.Mutex
var settingAfterSelectHooks []SettingHook

var settingBeforeInsertMu sync.Mutex
var settingBeforeInsertHooks []SettingHook
var settingAfterInsertMu sync.Mutex
var settingAfterInsertHooks []SettingHook

var settingBeforeUpdateMu sync.Mutex
var settingBeforeUpdateHooks []SettingHook
var settingAfterUpdateMu sync.Mutex
var settingAfterUpdateHooks []SettingHook

var settingBeforeDeleteMu sync.Mutex
var settingBeforeDeleteHooks []SettingHook
var settingAfterDeleteMu sync.Mutex
var settingAfterDeleteHooks []SettingHook

var settingBeforeUpsertMu sync.Mutex
var settingBeforeUpsertHooks []SettingHook
var settingAfterUpsertMu sync.Mutex
var settingAfterUpsertHooks []SettingHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Setting) doAfterSelectHooks(exec boil.Executor) (err error) {
	for _, hook := range settingAfterSelectHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Setting) doBeforeInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range settingBeforeInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Setting) doAfterInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range settingAfterInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Setting) doBeforeUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range settingBeforeUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Setting) doAfterUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range settingAfterUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Setting) doBeforeDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range settingBeforeDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Setting) doAfterDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range settingAfterDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Setting) doBeforeUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range settingBeforeUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Setting) doAfterUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range settingAfterUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddSettingHook registers your hook function for all future operations.
func AddSettingHook(hookPoint boil.HookPoint, settingHook SettingHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		settingAfterSelectMu.Lock()
		settingAfterSelectHooks = append(settingAfterSelectHooks, settingHook)
		settingAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		settingBeforeInsertMu.Lock()
		settingBeforeInsertHooks = append(settingBeforeInsertHooks, settingHook)
		settingBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		settingAfterInsertMu.Lock()
		settingAfterInsertHooks = append(settingAfterInsertHooks, settingHook)
		settingAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		settingBeforeUpdateMu.Lock()
		settingBeforeUpdateHooks = append(settingBeforeUpdateHooks, settingHook)
		settingBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		settingAfterUpdateMu.Lock()
		settingAfterUpdateHooks = append(settingAfterUpdateHooks, settingHook)
		settingAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		settingBeforeDeleteMu.Lock()
		settingBeforeDeleteHooks = append(settingBeforeDeleteHooks, settingHook)
		settingBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		settingAfterDeleteMu.Lock()
		settingAfterDeleteHooks = append(settingAfterDeleteHooks, settingHook)
		settingAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		settingBeforeUpsertMu.Lock()
		settingBeforeUpsertHooks = append(settingBeforeUpsertHooks, settingHook)
		settingBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		settingAfterUpsertMu.Lock()
		settingAfterUpsertHooks = append(settingAfterUpsertHooks, settingHook)
		settingAfterUpsertMu.Unlock()
	}
}

// One returns a single setting record from the query.
func (q settingQuery) One(exec boil.Executor) (*Setting, error) {
	o := &Setting{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(nil, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for settings")
	}

	if err := o.doAfterSelectHooks(exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all Setting records from the query.
func (q settingQuery) All(exec boil.Executor) (SettingSlice, error) {
	var o []*Setting

	err := q.Bind(nil, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Setting slice")
	}

	if len(settingAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all Setting records in the query.
func (q settingQuery) Count(exec boil.Executor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow(exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count settings rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q settingQuery) Exists(exec boil.Executor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow(exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if settings exists")
	}

	return count > 0, nil
}

// Settings retrieves all the records using an executor.
func Settings(mods ...qm.QueryMod) settingQuery {
	mods = append(mods, qm.From("\"settings\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"settings\".*"})
	}

	return settingQuery{q}
}

// FindSetting retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindSetting(exec boil.Executor, key null.String, selectCols ...string) (*Setting, error) {
	settingObj := &Setting{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"settings\" where \"key\"=?", sel,
	)

	q := queries.Raw(query, key)

	err := q.Bind(nil, exec, settingObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from settings")
	}

	if err = settingObj.doAfterSelectHooks(exec); err != nil {
		return settingObj, err
	}

	return settingObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Setting) Insert(exec boil.Executor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no settings provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(settingColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	settingInsertCacheMut.RLock()
	cache, cached := settingInsertCache[key]
	settingInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			settingAllColumns,
			settingColumnsWithDefault,
			settingColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(settingType, settingMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(settingType, settingMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"settings\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"settings\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into settings")
	}

	if !cached {
		settingInsertCacheMut.Lock()
		settingInsertCache[key] = cache
		settingInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(exec)
}

// Update uses an executor to update the Setting.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Setting) Update(exec boil.Executor, columns boil.Columns) error {
	var err error
	if err = o.doBeforeUpdateHooks(exec); err != nil {
		return err
	}
	key := makeCacheKey(columns, nil)
	settingUpdateCacheMut.RLock()
	cache, cached := settingUpdateCache[key]
	settingUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			settingAllColumns,
			settingPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return errors.New("models: unable to update settings, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"settings\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 0, wl),
			strmangle.WhereClause("\"", "\"", 0, settingPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(settingType, settingMapping, append(wl, settingPrimaryKeyColumns...))
		if err != nil {
			return err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}
	_, err = exec.Exec(cache.query, values...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update settings row")
	}

	if !cached {
		settingUpdateCacheMut.Lock()
		settingUpdateCache[key] = cache
		settingUpdateCacheMut.Unlock()
	}

	return o.doAfterUpdateHooks(exec)
}

// UpdateAll updates all rows with the specified column values.
func (q settingQuery) UpdateAll(exec boil.Executor, cols M) error {
	queries.SetUpdate(q.Query, cols)

	_, err := q.Query.Exec(exec)
	if err != nil {
		return errors.Wrap(err, "models: unable to update all for settings")
	}

	return nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o SettingSlice) UpdateAll(exec boil.Executor, cols M) error {
	ln := int64(len(o))
	if ln == 0 {
		return nil
	}

	if len(cols) == 0 {
		return errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), settingPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"settings\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, settingPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}
	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update all in setting slice")
	}

	return nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Setting) Upsert(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no settings provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(settingColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	settingUpsertCacheMut.RLock()
	cache, cached := settingUpsertCache[key]
	settingUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			settingAllColumns,
			settingColumnsWithDefault,
			settingColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			settingAllColumns,
			settingPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert settings, could not build update column list")
		}

		ret := strmangle.SetComplement(settingAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(settingPrimaryKeyColumns))
			copy(conflict, settingPrimaryKeyColumns)
		}
		cache.query = buildUpsertQuerySQLite(dialect, "\"settings\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(settingType, settingMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(settingType, settingMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert settings")
	}

	if !cached {
		settingUpsertCacheMut.Lock()
		settingUpsertCache[key] = cache
		settingUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(exec)
}

// Delete deletes a single Setting record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Setting) Delete(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no Setting provided for delete")
	}

	if err := o.doBeforeDeleteHooks(exec); err != nil {
		return err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), settingPrimaryKeyMapping)
	sql := "DELETE FROM \"settings\" WHERE \"key\"=?"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}
	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete from settings")
	}

	if err := o.doAfterDeleteHooks(exec); err != nil {
		return err
	}

	return nil
}

// DeleteAll deletes all matching rows.
func (q settingQuery) DeleteAll(exec boil.Executor) error {
	if q.Query == nil {
		return errors.New("models: no settingQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	_, err := q.Query.Exec(exec)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from settings")
	}

	return nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o SettingSlice) DeleteAll(exec boil.Executor) error {
	if len(o) == 0 {
		return nil
	}

	if len(settingBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), settingPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"settings\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, settingPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}
	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from setting slice")
	}

	if len(settingAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	return nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Setting) Reload(exec boil.Executor) error {
	ret, err := FindSetting(exec, o.Key)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *SettingSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := SettingSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), settingPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"settings\".* FROM \"settings\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, settingPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(nil, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in SettingSlice")
	}

	*o = slice

	return nil
}

// SettingExists checks if the Setting row exists.
func SettingExists(exec boil.Executor, key null.String) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"settings\" where \"key\"=? limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, key)
	}
	row := exec.QueryRow(sql, key)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if settings exists")
	}

	return exists, nil
}

// Exists checks if the Setting row exists.
func (o *Setting) Exists(exec boil.Executor) (bool, error) {
	return SettingExists(exec, o.Key)
}
